apiVersion: apps/v1
kind: Deployment
metadata:
  name: american-predictor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wslmac-american-predictor
  template:
    metadata:
      labels:
        app: wslmac-american-predictor
        environment : dev
    spec:
      containers:
      - name: american-predictor
        image: docker.io/wslmac/american-predictor:03
        ports:
        - containerPort: 5027